services:
  - type: web
    name: grupo15-api
    env: python
    plan: free
    branch: develop
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production